[[redirects]]
from = "/.well-known/apple-app-site-association"
to = "/.netlify/functions/asa"
status = 200
force = true


[[redirects]]
from = "/*"
to = "/web-build/index.html"
status = 200
force = true